# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_goods_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_front_image_url',
            field=models.CharField(default='', max_length=300, verbose_name='封面图片URL'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='描述图片'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='image',
            field=models.ImageField(max_length=200, upload_to='brands/'),
        ),
    ]
